# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/SYSTEM/Programming/Python Projects/Quiz/ui/quiz_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quiz_list(object):
    def setupUi(self, quiz_list):
        quiz_list.setObjectName("quiz_list")
        quiz_list.setEnabled(True)
        quiz_list.resize(378, 450)
        self.gridLayout = QtWidgets.QGridLayout(quiz_list)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(quiz_list)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_lbl = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_lbl.sizePolicy().hasHeightForWidth())
        self.title_lbl.setSizePolicy(sizePolicy)
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.gridLayout_2.addWidget(self.title_lbl, 0, 1, 1, 1)
        self.settings_btn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_btn.sizePolicy().hasHeightForWidth())
        self.settings_btn.setSizePolicy(sizePolicy)
        self.settings_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.settings_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.settings_btn.setText("")
        self.settings_btn.setObjectName("settings_btn")
        self.gridLayout_2.addWidget(self.settings_btn, 0, 2, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.manage_quiz = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manage_quiz.sizePolicy().hasHeightForWidth())
        self.manage_quiz.setSizePolicy(sizePolicy)
        self.manage_quiz.setObjectName("manage_quiz")
        self.gridLayout_2.addWidget(self.manage_quiz, 2, 0, 1, 3)
        self.quiz_lst_box = QtWidgets.QListWidget(self.frame)
        self.quiz_lst_box.setFocusPolicy(QtCore.Qt.NoFocus)
        self.quiz_lst_box.setStyleSheet("")
        self.quiz_lst_box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.quiz_lst_box.setFrameShadow(QtWidgets.QFrame.Plain)
        self.quiz_lst_box.setProperty("showDropIndicator", False)
        self.quiz_lst_box.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.quiz_lst_box.setUniformItemSizes(True)
        self.quiz_lst_box.setObjectName("quiz_lst_box")
        self.gridLayout_2.addWidget(self.quiz_lst_box, 1, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(quiz_list)
        QtCore.QMetaObject.connectSlotsByName(quiz_list)

    def retranslateUi(self, quiz_list):
        _translate = QtCore.QCoreApplication.translate
        quiz_list.setWindowTitle(_translate("quiz_list", "Quiz app"))
        self.title_lbl.setText(_translate("quiz_list", "Available Quiz"))
        self.manage_quiz.setText(_translate("quiz_list", "Manage Quiz"))
