# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/SYSTEM/Programming/Python Projects/Quiz/ui/quiz_selected.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_quiz_selected(object):
    def setupUi(self, quiz_selected):
        quiz_selected.setObjectName("quiz_selected")
        quiz_selected.resize(257, 242)
        self.gridLayout = QtWidgets.QGridLayout(quiz_selected)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(quiz_selected)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.back = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMinimumSize(QtCore.QSize(50, 50))
        self.back.setText("")
        self.back.setObjectName("back")
        self.gridLayout_2.addWidget(self.back, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modify_quiz = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modify_quiz.sizePolicy().hasHeightForWidth())
        self.modify_quiz.setSizePolicy(sizePolicy)
        self.modify_quiz.setMinimumSize(QtCore.QSize(0, 50))
        self.modify_quiz.setObjectName("modify_quiz")
        self.verticalLayout.addWidget(self.modify_quiz)
        self.start_quiz = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_quiz.sizePolicy().hasHeightForWidth())
        self.start_quiz.setSizePolicy(sizePolicy)
        self.start_quiz.setMinimumSize(QtCore.QSize(0, 50))
        self.start_quiz.setObjectName("start_quiz")
        self.verticalLayout.addWidget(self.start_quiz)
        self.gridLayout_2.addWidget(self.frame_2, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(quiz_selected)
        QtCore.QMetaObject.connectSlotsByName(quiz_selected)

    def retranslateUi(self, quiz_selected):
        _translate = QtCore.QCoreApplication.translate
        quiz_selected.setWindowTitle(_translate("quiz_selected", "Form"))
        self.back.setAccessibleName(_translate("quiz_selected", "back"))
        self.modify_quiz.setAccessibleName(_translate("quiz_selected", "quiz_selected_btns"))
        self.modify_quiz.setText(_translate("quiz_selected", "Modify Quiz"))
        self.start_quiz.setAccessibleName(_translate("quiz_selected", "quiz_selected_btns"))
        self.start_quiz.setText(_translate("quiz_selected", "Start Quiz"))
