# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/SYSTEM/Programming/Python Projects/Quiz/ui/welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from typing import List


class Ui_welcome(object):
    def setupUi(self, welcome):
        self.hosts_lbl:List[QtWidgets.QLabel] = []
        
        welcome.setObjectName("welcome")
        welcome.resize(662, 471)
        self.gridLayout = QtWidgets.QGridLayout(welcome)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hostedBy = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostedBy.sizePolicy().hasHeightForWidth())
        self.hostedBy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hostedBy.setFont(font)
        self.hostedBy.setAlignment(QtCore.Qt.AlignCenter)
        self.hostedBy.setObjectName("hostedBy")
        self.gridLayout_2.addWidget(self.hostedBy, 2, 0, 1, 2)
        self.welcome_title = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_title.sizePolicy().hasHeightForWidth())
        self.welcome_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.welcome_title.setFont(font)
        self.welcome_title.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_title.setObjectName("welcome_title")
        self.gridLayout_2.addWidget(self.welcome_title, 0, 0, 1, 2)
        self.topic = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topic.sizePolicy().hasHeightForWidth())
        self.topic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(29)
        self.topic.setFont(font)
        self.topic.setAlignment(QtCore.Qt.AlignCenter)
        self.topic.setObjectName("topic")
        self.gridLayout_2.addWidget(self.topic, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.start_quiz = QtWidgets.QPushButton(welcome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_quiz.sizePolicy().hasHeightForWidth())
        self.start_quiz.setSizePolicy(sizePolicy)
        self.start_quiz.setMinimumSize(QtCore.QSize(0, 50))
        self.start_quiz.setObjectName("start_quiz")
        self.gridLayout.addWidget(self.start_quiz, 2, 0, 1, 1)

        self.retranslateUi(welcome)
        QtCore.QMetaObject.connectSlotsByName(welcome)

    def retranslateUi(self, welcome):
        _translate = QtCore.QCoreApplication.translate
        welcome.setWindowTitle(_translate("welcome", "Dialog"))
        self.hostedBy.setText(_translate("welcome", "Hosted By :"))
        self.welcome_title.setText(_translate("welcome", "Welcome you all to the QUIZ on"))
        self.topic.setText(_translate("welcome", "Topic"))
        self.start_quiz.setText(_translate("welcome", "Start Quiz"))
