# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/naveen/Desktop/Quiz/Tests/Welcome/Welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    
    def __init__(self,  Hosts, Topic_name):
        self.Dialog = QtWidgets.QDialog()
        self.Hosts = Hosts
        self.Topic_name = Topic_name
        
        self.setup()
        self.Dialog.show()
    
    def setup(self):
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(662, 471)
        
        
        self.gridLayout = QtWidgets.QGridLayout(self.Dialog)
        self.gridLayout.setObjectName("gridLayout")
        
        
        self.frame = QtWidgets.QFrame(self.Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        
        self.Welcome = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Welcome.sizePolicy().hasHeightForWidth())
        self.Welcome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Welcome.setFont(font)
        self.Welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.Welcome.setText("Welcome you all to the QUIZ on")
        self.Welcome.setObjectName("Welcome")
        self.gridLayout_2.addWidget(self.Welcome, 0, 0, 1, len(self.Hosts))
        
        
        self.Topic = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Topic.sizePolicy().hasHeightForWidth())
        self.Topic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(29)
        self.Topic.setFont(font)
        self.Topic.setAlignment(QtCore.Qt.AlignCenter)
        self.Topic.setText(self.Topic_name)
        self.Topic.setObjectName("Topic")
        self.gridLayout_2.addWidget(self.Topic, 1, 0, 1, len(self.Hosts))
        
        
        self.HostedBy = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostedBy.sizePolicy().hasHeightForWidth())
        self.HostedBy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.HostedBy.setFont(font)
        self.HostedBy.setAlignment(QtCore.Qt.AlignCenter)
        self.HostedBy.setText("Hosted By :")
        self.HostedBy.setObjectName("HostedBy")
        self.gridLayout_2.addWidget(self.HostedBy, 2, 0, 1, len(self.Hosts))
        
        font = QtGui.QFont()
        font.setPointSize(20)
        
        for i in range(len(self.Hosts)):
            exec(f'''self.Host_{i+1} = QtWidgets.QLabel(self.frame)''')            
            eval(f'''self.Host_{i+1}.setFont(font)''')
            eval(f'''self.Host_{i+1}.setAlignment(QtCore.Qt.AlignCenter)''')
            eval(f'''self.Host_{i+1}.setText('{self.Hosts[i]}')''')
            eval(f'''self.Host_{i+1}.setObjectName('Host_{i+1}')''')
            eval(f'''self.Host_{i+1}.setStyleSheet("""border: 3px solid black""")''')
            eval(f'''self.gridLayout_2.addWidget(self.Host_{i+1}, 3, {i}, 1, 1)''')
        
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)

        # self.retranslateUi(Dialog)
        # QtCore.QMetaObject.connectSlotsByName(Dialog)

    # def retranslateUi(self, Dialog):
    #     _translate = QtCore.QCoreApplication.translate
    #     Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    #     self.Welcome.setText(_translate("Dialog", "Welcome you all to the QUIZ on"))
    #     self.Topic.setText(_translate("Dialog", "Engineering Physics"))
    #     self.HostedBy.setText(_translate("Dialog", "Hosted By :"))
    #     self.Host_1.setText(_translate("Dialog", "Nagi Pragalathan"))
    #     self.label_7.setText(_translate("Dialog", "Heamenth"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(['Nagi Pragalathan', 'Heamenth'], 'Engineering Graphics')
    # ui.setupUi()
    # Dialog.show()
    sys.exit(app.exec_())
